export const languages = {
  es: 'Español',
  en: 'English',
}

export const defaultLang = 'es'

export const ui = {
  es: {
    'home.alert':
      'Las imágenes del juego están diseñadas por IA, por lo que su resultado en expresiones faciales es limitada.',
    'home.card.title': '¿Dónde está',
    'home.card.midu':
      'se encuentra en una batalla campal entre los fanáticos de React y los entusiastas de Angular. Pero como mago de JavaScript, intentará escapar de toda polémica. ¿Sobrevirá a la batalla? ¡Encuéntralo antes de que lo funen!',
    'home.card.altman':
      'está buscando ansiosamente financiamiento para crear Chat-GPT5, pero para ello, se ha convertido en una momia más para pasar desapercibido con otras viejas momias con mucho dinero. ¿Dónde estará Altman?',
    'home.card.php':
      'está en paradero desconocido, algunos dicen que está muerto y otros más vivo que nunca. Búscalo en el último lugar visto, en el cementerio...',
    'home.card.gaga':
      'se ha vuelto a transformar por 4931 vez. Yo sigo sin saber reconocerla, pero dicen que se ha convertido en una vampira. Encuéntrala antes de que vuelva a cambiar de look y pídele un autógrafo de mi parte.',
    'home.card.colby':
      'lleva más de 837 horas despierto contestando las preguntas del foro de Discord y se ha convertido en un zombie. Encuentrálo, dale las gracias por toda su atención y mándalo a descansar.',
    'home.card.collaborate': '+ Colaborar',
    'home.footer.1': 'para el equipo de',
    'home.footer.2': 'Cloudinary',
    'home.footer.3': ', Midu y la gente de',
    'home.footer.4': 'Twitch',
    'home.footer.author': 'Creado por',
    'home.footer.info':
      'Aunque no hay revisión de código, he intentado hacer el juego lo más simple posible y siguiendo las buenas prácticas',

    'game.backBtn': '← Volver',
    'game.correct.msg': 'CORRECTO! 🥳🎊👏🏼',
    'game.error.attempt': 'Incorrecto',
    'game.error.marker': 'Marca la posición!',
    'game.info.1': 'Para marcar una respuesta,',
    'game.info.2': 'centra la imagen',
    'game.info.3': 'y marca en el lugar aproximado con el botón derecho.',
    'game.miduHelpTxt':
      'Activa la miduAyuda para obtener una pista de donde está',
    'game.miduHelpTxt.midu':
      'Midu se encuentra en un lugar seguro, observando la batalla desde su setup junto a miduGato y su framework favorito.',
    'game.miduHelpTxt.altman':
      'Altman sigue de muy cerca la charla, al acecho de conseguir su sueño de una nueva IA.',
    'game.miduHelpTxt.php':
      'PHP está junto a su gran tumba, pero se resiste a entrar en ella.',
    'game.miduHelpTxt.gaga':
      'Lady Gaga está descansando apartada de la multitud en su castillo de vampira con vistas al mar.',
    'game.miduHelpTxt.colby':
      'Colby está siendo engullido por un participante que no consiguió resolver su duda.',

    'game.cloudinaryHelp.title': 'La Cloudinary ayuda',
    'game.cloudinaryHelp.text': 'Mejorando la resolución, espere un momento...',
    'game.miduHelp.title': 'La MiduAyuda',
    'game.centerImg.title': 'Centrar la imágen',
    'game.attemptBtn': 'Realizar intento',

    'game.surrenderTxt.midu':
      'Me rindo... Dejaré morir a Midu y que se lo coman en X',
    'game.surrenderTxt.altman': 'Me rindo...Dejar que Altman se vaya al paro',
    'game.surrenderTxt.php':
      'Me rindo... Dejaré que PHP muere dejando su gran legado',
    'game.surrenderTxt.gaga':
      'Me rindo... No encuentra la enésima tranformación de Lady Gaga',
    'game.surrenderTxt.colby':
      'Me rindo... Dejar que Colby muera por no descansar durante la Hackatón',
    'game.surrenderBtn': 'Resolver',

    'game.helps.cloudinary1': '- ¡La',
    'game.helps.cloudinary2': 'Cloudinary ayuda',
    'game.helps.cloudinary3':
      'te permite mejorar la resolución de un trozo de imagen en alta resolución! ¡¡Pero tendrás que observar rápido!! ¡Porque a los 10 segundos la imágen vuelve a la calidad original!',

    'game.helps.midu1': '- La',
    'game.helps.midu2': 'miduAyuda',
    'game.helps.midu3': 'te da una pequeña pista de donde se encuentra',
  },
  en: {
    'home.alert':
      'The game images are generated by AI, so their results in facial expressions are limited.',
    'home.card.title': 'Where is',
    'home.card.midu':
      'is in a fierce battle between React fans and Angular enthusiasts. But as a JavaScript wizard, he will try to escape all controversy. Will he survive the battle? Find out before he gets canceled.',
    'home.card.altman':
      'is eagerly seeking funding to create Chat-GPT5. However, to do so, he has become another mummy to blend in with other old mummies wealthy. Where will Altman be?',
    'home.card.php':
      'is missing, some say he is dead while others claim he is more alive than ever. Look for him in the last place they were seen, in the cemetery...',
    'home.card.gaga':
      "has transformed for the 4931st time. I still can't recognize her, but they say she has become a vampire. Find her before she changes her look again and ask for an autograph on my behalf.",
    'home.card.colby':
      'has been awake for over 837 hours answering questions on the Discord forum and has become a zombie. Find him, thank him for all his attention and send him to rest.',
    'home.card.collaborate': '+ Collaborate',
    'home.footer.1': 'for the',
    'home.footer.2': 'Cloudinary',
    'home.footer.3': 'team, Midu and the people of',
    'home.footer.4': 'Twitch',
    'home.footer.author': 'Created by',
    'home.footer.info':
      'Although there is no code review, I have tried to make the game as simple as possible and following best practices.',

    'game.backBtn': '← Back',
    'game.correct.msg': 'CORRECT! 🥳🎊👏🏼',
    'game.error.attempt': 'Incorrect',
    'game.error.marker': 'Mark the position!',
    'game.info.1': 'To mark an answer,',
    'game.info.2': 'center the image',
    'game.info.3': 'and mark the approximate location with the right button.',
    'game.miduHelpTxt': 'Activate MiduHelp to get a hint about where he is',
    'game.miduHelpTxt.midu':
      'Midu is in a safe place, watching the battle from his setup alongside miduGato and his favorite framework.',
    'game.miduHelpTxt.altman':
      'Altman closely follows the conversation, eager to achieve his dream of a new AI.',
    'game.miduHelpTxt.php':
      "PHP is standing next to it's large grave but refuses to enter it.",
    'game.miduHelpTxt.gaga':
      'Lady Gaga is resting away from the crowd in her vampire castle overlooking the sea.',
    'game.miduHelpTxt.colby':
      "Colby is being swallowed by a participant who couldn't solve their question.",

    'game.cloudinaryHelp.title': 'The Cloudinary help',
    'game.cloudinaryHelp.text':
      'Improving the resolution, please wait a moment...',
    'game.miduHelp.title': 'The MiduHelp',
    'game.centerImg.title': 'Center the image',
    'game.attemptBtn': 'Make attempt',

    'game.surrenderTxt.midu':
      'I give up... I will let Midu die and be eaten in X',
    'game.surrenderTxt.altman': 'I give up... Let Altman go on unemployment',
    'game.surrenderTxt.php':
      'I give up... I will let PHP die, leaving behind its great legacy',
    'game.surrenderTxt.gaga':
      "I give up... I can't find Lady Gaga's umpteenth transformation",
    'game.surrenderTxt.colby':
      'I give up... Let Colby die from not resting during the Hackathon',
    'game.surrenderBtn': 'Resolve',

    'game.helps.cloudinary1': '- The',
    'game.helps.cloudinary2': 'Cloudinary help',
    'game.helps.cloudinary3':
      'allows you to enhance the resolution of a piece of image in high resolution! But you will have to observe quickly!! Because after 10 seconds, the image returns to its original quality!',

    'game.helps.midu1': '- The',
    'game.helps.midu2': 'MiduHelp',
    'game.helps.midu3': 'gives you a small hint about',
  },
} as const
